[colors.bright]
black = "0x657b83"
blue = "0x0a4b78"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0x6c71c4"
red = "0xdc322f"
white = "0xfdf6e3"
yellow = "0xb58900"

[colors.cursor]
cursor = "0x93a1a1"
text = "0xf7e1a3"

[colors.normal]
black = "0x002b36"
blue = "0xdea214"
cyan = "0x2aa198"
green = "0x255380"
magenta = "0x6c71c4"
red = "0xdc322f"
white = "0x93a1a1"
yellow = "0xb58900"

[colors.primary]
background = "0x1d1f23"
foreground = "0x657b83"

[env]
TERM = "xterm-256color"

[font]
size = 11.5

[font.bold]
family = "BigBlueTerm437 Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "BigBlueTerm437 Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "BigBlueTerm437 Nerd Font Mono"
style = "Italic"

[font.normal]
family = "BigBlueTerm437 Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 5000

[window]
startup_mode = "Maximized"
title = ""
dynamic_title = false
dynamic_padding = true

[cursor]
blink_interval = 500
blink_timeout = 0

[cursor.style]
blinking = "Always"

[terminal]
osc52 = "CopyPaste"

[keyboard]
bindings = [
	{ key = "V", mods = "Control", action = "Paste" },
	{ key = "C", mods = "Control", action = "Copy" },
	{ key = "F11", action = "ToggleFullscreen"}
]
